server:
  port: 9090
  #servlet:
  # context-path: /erp-api-v1

spring:
  datasource:
    name: ${DB_NAME:userData}
    host: ${DB_HOST:localhost}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.name}?createDatabaseIfNotExist=true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # Changer en << update >> d?s qu'on initialise la db
    show-sql: false
  application:
    name: angular_crud_back
